### ISSUE TITLE
init.d scripts didn't run on redmi4x, injector v1.4,  magisk 16.4

### ISSUE THREAD

**Issue by fres-a** [Zackptg5/Init.d-Injector#2]
i tried run simple script for test, and he didnt run. name script 54d.sh(chmod 755)
```
#!system/bin/sh
touch /sdcard/1.txt
```
and i tied
```
#!system/bin/sh
su && touch /sdcard/1.txt
```
and 
```
#!system/bin/sh
su -c touch /sdcard/1.txt
```
what is my problem?

**Comment by fres-a** [comment]
strange any action on sdcard didnr work, but in others it's work

**Comment by Zackptg5** [comment]
That's because of mounting. By default, init.d scripts run as post-fs-data scripts. At this point, the /sdcard symlink hasn't been created yet so you'll want to use it's real path: /data/media/0
If you're running it as a late_start, you probably could use /sdcard but I recommend using /storage/emulated/0 instead as it's more universal for internal storage of Android devices
